"""
Explainability Audit Logging Module for BlasterOPT / BlastOpt Botswana.

Provides an immutable, append-only SQLite audit log recording every prediction explanation generated
by the Explainability Layer (SHAP values, LIME feature weights, natural language summary, user ID, timestamp).

Domain Context & Regulatory Accountability:
------------------------------------------
Under Botswana's Mines, Quarries, Works and Machinery Act (Cap. 44:02) and Department of Mines guidelines,
post-blast environmental impact investigations (e.g. wall damage, citizen complaints regarding seismic ground vibration,
or flyrock incidents) require an immutable audit trail.
By storing every explanation generated by the AI model in an append-only SQLite database table,
BlasterOPT ensures that mining engineers, certified blasters, and regulatory inspectors can trace
the exact AI reasoning and inputs that influenced blast design approvals.
"""

import json
import sqlite3
import datetime
from typing import Dict, Any, List, Optional, Union


def _init_db(db_path: str = "data/processed/explainability_audit.db") -> sqlite3.Connection:
    """Initializes SQLite database connection and creates explanation_audit_log table if not exists."""
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS explanation_audit_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            prediction_id TEXT NOT NULL,
            shap_values_json TEXT NOT NULL,
            lime_weights_json TEXT NOT NULL,
            natural_language TEXT NOT NULL,
            user_id TEXT NOT NULL
        )
        """
    )
    conn.commit()
    return conn


def log_explanation(
    prediction_id: str,
    shap_values: Union[Dict[str, float], List[float], Any],
    lime_weights: Union[Dict[str, float], Any],
    natural_language: str,
    user_id: str = "CHIEF_BLASTER_01",
    db_path: str = "data/processed/explainability_audit.db",
) -> Dict[str, Any]:
    """
    Stores an explanation record immutably in an append-only SQLite database.

    Parameters:
    -----------
    prediction_id : str
        Unique prediction or blast design identifier (e.g., "PRED_JWA_2026_001").
    shap_values : Union[Dict[str, float], List[float], Any]
        SHAP values dictionary or list.
    lime_weights : Union[Dict[str, float], Any]
        LIME feature weights dictionary.
    natural_language : str
        Plain-English natural language explanation summary text.
    user_id : str, default="CHIEF_BLASTER_01"
        User ID or system agent identifier generating the prediction.
    db_path : str, default="data/processed/explainability_audit.db"
        Path to SQLite audit database file.

    Returns:
    --------
    Dict[str, Any]
        Dict containing logged record status and inserted row ID.
    """
    timestamp = datetime.datetime.now(datetime.timezone.utc).isoformat()

    # Serialize SHAP and LIME payloads to JSON
    if isinstance(shap_values, (dict, list)):
        shap_json = json.dumps(shap_values)
    else:
        shap_json = json.dumps(str(shap_values))

    if isinstance(lime_weights, (dict, list)):
        lime_json = json.dumps(lime_weights)
    else:
        lime_json = json.dumps(str(lime_weights))

    conn = _init_db(db_path)
    cursor = conn.cursor()

    cursor.execute(
        """
        INSERT INTO explanation_audit_log
        (timestamp, prediction_id, shap_values_json, lime_weights_json, natural_language, user_id)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (timestamp, prediction_id, shap_json, lime_json, natural_language, user_id),
    )

    conn.commit()
    row_id = cursor.lastrowid
    conn.close()

    return {
        "status": "success",
        "row_id": row_id,
        "prediction_id": prediction_id,
        "timestamp": timestamp,
        "user_id": user_id,
    }


def get_recent_explanations(
    limit: int = 50,
    db_path: str = "data/processed/explainability_audit.db",
) -> List[Dict[str, Any]]:
    """
    Retrieves recent explanation records from the immutable SQLite audit log.

    Parameters:
    -----------
    limit : int, default=50
        Maximum number of recent records to retrieve.
    db_path : str, default="data/processed/explainability_audit.db"
        Path to SQLite audit database file.

    Returns:
    --------
    List[Dict[str, Any]]
        List of audit record dictionaries.
    """
    conn = _init_db(db_path)
    cursor = conn.cursor()

    cursor.execute(
        """
        SELECT id, timestamp, prediction_id, shap_values_json, lime_weights_json, natural_language, user_id
        FROM explanation_audit_log
        ORDER BY id DESC
        LIMIT ?
        """,
        (limit,),
    )

    rows = cursor.fetchall()
    conn.close()

    records = []
    for row in rows:
        records.append({
            "id": row[0],
            "timestamp": row[1],
            "prediction_id": row[2],
            "shap_values_json": row[3],
            "lime_weights_json": row[4],
            "natural_language": row[5],
            "user_id": row[6],
        })

    return records
