"""
PDF Report Generator for BlastOpt Botswana.

Generates downloadable PDF reports summarizing optimization objectives,
top 5 recommended blast designs, and embedded fragmentation curves using fpdf2.
"""

import os
import tempfile
from typing import List, Dict, Any
from fpdf import FPDF
import plotly.io as pio

from src.visualize import plot_kuz_ram_curve


class BlastReportPDF(FPDF):
    """Custom FPDF class for BlastOpt Botswana PDF report layout."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(25, 118, 210)  # Blue title
        self.cell(0, 10, "BlastOpt Botswana - Optimization Report", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "AI-Driven Blasting Optimization Suite", border=False, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by BlastOpt Botswana", align="C")


def generate_pdf(
    designs: List[Dict[str, Any]],
    filename: str = "blast_optimization_report.pdf",
    objectives_summary: str = "Minimize D&B cost ($/t) subject to vibration (PPV), flyrock, and fragmentation constraints.",
    constraints_info: Dict[str, Any] = None,
) -> str:
    """
    Generates a PDF report summarizing blast optimization results and top 5 recommended designs.

    Parameters:
    -----------
    designs : List[Dict[str, Any]]
        List of dictionaries containing top recommended blast design parameters and outputs.
    filename : str, default="blast_optimization_report.pdf"
        Target output file path for the generated PDF.
    objectives_summary : str
        Textual summary of optimization objectives.
    constraints_info : Dict[str, Any], optional
        Dictionary specifying constraint limits (Max PPV, Max Flyrock, Target d50 range).

    Returns:
    --------
    str
        File path of generated PDF report.
    """
    pdf = BlastReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Section 1: Optimization Summary & Constraints
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "1. Optimization Objectives & Constraints Summary", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, f"Objectives: {objectives_summary}")
    pdf.ln(2)

    if constraints_info:
        pdf.cell(0, 6, f"- Max Ground Vibration Limit (PPV): {constraints_info.get('max_ppv', 'N/A')} mm/s", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"- Max Flyrock Distance Limit: {constraints_info.get('max_flyrock', 'N/A')} m", new_x="LMARGIN", new_y="NEXT")
        d50_range = constraints_info.get("d50_range", ("N/A", "N/A"))
        pdf.cell(0, 6, f"- Target d50 Fragmentation Range: {d50_range[0]} - {d50_range[1]} mm", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Section 2: Top Recommended Blast Designs Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "2. Top Recommended Blast Design Configurations", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table Header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(225, 240, 255)
    headers = ["Rank", "Burden (m)", "Spacing (m)", "Stemming (m)", "PF (kg/m3)", "d50 (mm)", "PPV (mm/s)", "Cost ($/t)"]
    col_widths = [12, 22, 22, 24, 22, 22, 24, 22]

    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1, fill=True, align="C")
    pdf.ln()

    # Table Rows
    pdf.set_font("Helvetica", "", 8)
    for idx, item in enumerate(designs[:5], 1):
        p = item.get("parameters", {})
        o = item.get("outputs", {})

        pdf.cell(col_widths[0], 6, str(idx), border=1, align="C")
        pdf.cell(col_widths[1], 6, f"{p.get('burden_m', 0.0):.2f}", border=1, align="C")
        pdf.cell(col_widths[2], 6, f"{p.get('spacing_m', 0.0):.2f}", border=1, align="C")
        pdf.cell(col_widths[3], 6, f"{p.get('stemming_m', 0.0):.2f}", border=1, align="C")
        pdf.cell(col_widths[4], 6, f"{p.get('powder_factor_kg_m3', 0.0):.3f}", border=1, align="C")
        pdf.cell(col_widths[5], 6, f"{o.get('d50_mm', 0.0):.1f}", border=1, align="C")
        pdf.cell(col_widths[6], 6, f"{o.get('ppv_mms', 0.0):.2f}", border=1, align="C")
        pdf.cell(col_widths[7], 6, f"${o.get('cost_per_tonne_usd', 0.0):.2f}", border=1, align="C")
        pdf.ln()

    pdf.ln(6)

    # Section 3: Fragmentation Curve Plot for Best Design
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "3. Fragmentation Size Distribution Curve (Best Design)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    if designs:
        best_outputs = designs[0].get("outputs", {})
        best_d50 = best_outputs.get("d50_mm", 200.0)

        # Generate fragmentation plot image
        fig = plot_kuz_ram_curve(d50_mm=best_d50, n_uniformity=1.2, label="Best Recommended Design")

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp_img:
            img_path = tmp_img.name
            pio.write_image(fig, img_path, width=700, height=350)

        pdf.image(img_path, x=15, w=180)
        try:
            os.remove(img_path)
        except OSError:
            pass

    os.makedirs(os.path.dirname(filename) if os.path.dirname(filename) else ".", exist_ok=True)
    pdf.output(filename)
    return filename
